/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
 * Generated on: 13-May-2020 14:31:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 121
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int lowpass_length = 121;
Int16 lowpass[121] = {
        0,      0,      0,      0,      0,      0,      1,      2,      3,
        4,      4,      3,      0,     -4,     -9,    -14,    -18,    -20,
      -18,    -11,      0,     15,     32,     47,     58,     61,     53,
       32,      0,    -40,    -84,   -122,   -147,   -151,   -128,    -77,
        0,     94,    191,    275,    329,    335,    282,    169,      0,
     -206,   -421,   -612,   -738,   -764,   -659,   -405,      0,    540,
     1180,   1874,   2561,   3180,   3671,   3987,   4096,   3987,   3671,
     3180,   2561,   1874,   1180,    540,      0,   -405,   -659,   -764,
     -738,   -612,   -421,   -206,      0,    169,    282,    335,    329,
      275,    191,     94,      0,    -77,   -128,   -151,   -147,   -122,
      -84,    -40,      0,     32,     53,     61,     58,     47,     32,
       15,      0,    -11,    -18,    -20,    -18,    -14,     -9,     -4,
        0,      3,      4,      4,      3,      2,      1,      0,      0,
        0,      0,      0,      0
};
