/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 12-May-2020 13:16:03
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 121
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s32,30 -> [-2 2)  (auto determined)
 *   Product         : s27,30 -> [-6.250000e-02 6.250000e-02)  (auto determined)
 *   Accumulator     : s32,30 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
const int FIR_LP_1000_Hz_L = 121;
const int16_T FIR_LP_1000_Hz[121] = {
        0,      0,      0,      0,      1,      1,      1,      2,      2,
        2,      1,      1,      0,     -1,     -3,     -6,     -9,    -13,
      -18,    -23,    -29,    -36,    -43,    -51,    -58,    -66,    -72,
      -78,    -82,    -84,    -84,    -80,    -74,    -63,    -47,    -26,
        0,     32,     70,    114,    165,    221,    283,    350,    422,
      498,    577,    658,    740,    821,    901,    979,   1053,   1121,
     1183,   1237,   1283,   1320,   1346,   1363,   1368,   1363,   1346,
     1320,   1283,   1237,   1183,   1121,   1053,    979,    901,    821,
      740,    658,    577,    498,    422,    350,    283,    221,    165,
      114,     70,     32,      0,    -26,    -47,    -63,    -74,    -80,
      -84,    -84,    -82,    -78,    -72,    -66,    -58,    -51,    -43,
      -36,    -29,    -23,    -18,    -13,     -9,     -6,     -3,     -1,
        0,      1,      1,      2,      2,      2,      1,      1,      1,
        0,      0,      0,      0
};
