/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 12-May-2020 13:13:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 121
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
const int FIR_HP_1000_Hz_L = 121;
const int16_T FIR_HP_1000_Hz[121] = {
        0,      0,      0,      0,     -1,     -1,     -1,     -2,     -2,
       -2,     -1,     -1,      0,      1,      3,      6,      9,     13,
       18,     23,     29,     36,     43,     51,     58,     65,     72,
       78,     82,     84,     84,     80,     73,     62,     47,     26,
        0,    -32,    -70,   -114,   -164,   -220,   -282,   -350,   -421,
     -497,   -576,   -656,   -738,   -820,   -900,   -977,  -1050,  -1119,
    -1180,  -1235,  -1281,  -1317,  -1344,  -1360,  31403,  -1360,  -1344,
    -1317,  -1281,  -1235,  -1180,  -1119,  -1050,   -977,   -900,   -820,
     -738,   -656,   -576,   -497,   -421,   -350,   -282,   -220,   -164,
     -114,    -70,    -32,      0,     26,     47,     62,     73,     80,
       84,     84,     82,     78,     72,     65,     58,     51,     43,
       36,     29,     23,     18,     13,      9,      6,      3,      1,
        0,     -1,     -1,     -2,     -2,     -2,     -1,     -1,     -1,
        0,      0,      0,      0
};
