/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 12-May-2020 13:17:46
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I, Second-Order Sections
 * Number of Sections  : 6
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,15 -> [-1 1)
 * Input               : s16,15 -> [-1 1)
 * Output              : s36,31 -> [-16 16)
 * Numerator State     : s16,15 -> [-1 1)
 * Denominator State   : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,29 -> [-16 16)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 13
const int IIR_LP_1000_Hz_NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,2,1 };
const int16_T IIR_LP_1000_Hz_NUM[MWSPT_NSEC][3] = {
  {
    12314,      0,      0 
  },
  {
    16384, -32356,  16384 
  },
  {
    11540,      0,      0 
  },
  {
    16384, -32281,  16384 
  },
  {
     9975,      0,      0 
  },
  {
    16384, -32065,  16384 
  },
  {
     7130,      0,      0 
  },
  {
    16384, -31408,  16384 
  },
  {
     2900,      0,      0 
  },
  {
    16384, -28024,  16384 
  },
  {
     2020,      0,      0 
  },
  {
    16384,  16384,      0 
  },
  {
    16384,      0,      0 
  }
};
const int IIR_LP_1000_Hz_DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,2,1 };
const int16_T IIR_LP_1000_Hz_DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384, -32145,  16071 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -31412,  15371 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -30346,  14390 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -28635,  12843 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -26198,  10654 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -12345,      0 
  },
  {
    16384,      0,      0 
  }
};
