/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
 * Generated on: 12-May-2020 13:19:47
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,15 -> [-1 1)
 * Input               : s16,15 -> [-1 1)
 * Output              : s36,31 -> [-16 16)
 * Numerator State     : s16,15 -> [-1 1)
 * Denominator State   : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s34,29 -> [-16 16)
 * Denominator Accum   : s34,29 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int IIR_HP_1000_Hz_NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int16_T IIR_HP_1000_Hz_NUM[MWSPT_NSEC][3] = {
  {
    16202,      0,      0 
  },
  {
    16384, -32593,  16384 
  },
  {
    15898,      0,      0 
  },
  {
    16384, -32625,  16384 
  },
  {
    15648,      0,      0 
  },
  {
    16384, -32678,  16384 
  },
  {
    15470,      0,      0 
  },
  {
    16384, -32731,  16384 
  },
  {
    15378,      0,      0 
  },
  {
    16384, -32764,  16384 
  },
  {
    16384,      0,      0 
  }
};
const int IIR_HP_1000_Hz_DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int16_T IIR_HP_1000_Hz_DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0 
  },
  {
    16384, -32197,  16055 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -31624,  15445 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -31176,  14944 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -30872,  14588 
  },
  {
    16384,      0,      0 
  },
  {
    16384, -30719,  14404 
  },
  {
    16384,      0,      0 
  }
};
